{{- if and .Values.minio.enabled .Values.statesman.objectStorageSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.statesman.objectStorageSecret.name }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | quote }}
  OPENTACO_S3_BUCKET: {{ .Values.statesman.objectStorageSecret.bucket | quote }}
  OPENTACO_S3_REGION: {{ .Values.statesman.objectStorageSecret.region | quote }}
  AWS_ENDPOINT: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "opentaco-platform-reference.minio.fullname" .) .Release.Namespace .Values.minio.service.apiPort | quote }}
{{- if .Values.statesman.objectStorageSecret.prefix }}
  OPENTACO_S3_PREFIX: {{ .Values.statesman.objectStorageSecret.prefix | quote }}
{{- end }}
{{- if .Values.statesman.objectStorageSecret.awsRegion }}
  AWS_REGION: {{ .Values.statesman.objectStorageSecret.awsRegion | quote }}
{{- end }}
{{- end }}
